### ISSUE TITLE
Exception during processing!!! expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by felixding** [Jannchie/ComfyUI-J#21]
I encountered the following error while trying to change clothes using the workflow from the repository:

```
!!! Exception during processing!!! expected str, bytes or os.PathLike object, not list
Traceback (most recent call last):
  File "/home/felixding/projects/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felixding/projects/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felixding/projects/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felixding/projects/ComfyUI/custom_nodes/ComfyUI-J/__init__.py", line 467, in run
    self.pipeline_wrapper = PipelineWrapper(
                            ^^^^^^^^^^^^^^^^
  File "/home/felixding/projects/ComfyUI/custom_nodes/ComfyUI-J/pipelines/__init__.py", line 59, in __init__
    self.pipeline = JannchiePipeline.from_single_file(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felixding/miniconda3/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/felixding/miniconda3/lib/python3.12/site-packages/diffusers/loaders/single_file.py", line 409, in from_single_file
    cached_model_config_path = _download_diffusers_model_config_from_hub(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felixding/miniconda3/lib/python3.12/site-packages/diffusers/loaders/single_file.py", line 250, in _download_diffusers_model_config_from_hub
    cached_model_path = snapshot_download(
                        ^^^^^^^^^^^^^^^^^^
  File "/home/felixding/miniconda3/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/felixding/miniconda3/lib/python3.12/site-packages/huggingface_hub/_snapshot_download.py", line 149, in snapshot_download
    storage_folder = os.path.join(cache_dir, repo_folder_name(repo_id=repo_id, repo_type=repo_type))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not list
```

Here is the node that likely triggered the error:

<img width="655" alt="image" src="https://github.com/Jannchie/ComfyUI-J/assets/111456/ae588abd-9022-4616-a253-03344bb89dc7">

Additionally, is there a way to modify the workflow to enable swapping clothes from a garment image of my choosing?

**Comment by bbostock** [comment]
I am also having the same problem with the Diffusers Pipeline. Any ideas for a workaround or solution?

**Comment by masquerlin** [comment]
I have had this problem with the diffusers, but solve it by `pip install diffusers==0.26.3` . You need to degrade your diffusers version.

**Comment by quqiufeng** [comment]
why do not support the newer version of diffusers?

**Comment by Jannchie** [comment]
Fixed...
