### ISSUE TITLE
 Exception during processing!!! module 'comfy.model_management' has no attribute 'VAE_DTYPE'

### ISSUE THREAD

**Issue by sd50pcs2000** [Jannchie/ComfyUI-J#24]
!!! Exception during processing!!! module 'comfy.model_management' has no attribute 'VAE_DTYPE'
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-J\__init__.py", line 823, in run
    dtype=comfy.model_management.VAE_DTYPE,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.model_management' has no attribute 'VAE_DTYPE'

**Comment by sd50pcs2000** [comment]
![Uploading 屏幕截图 2024-07-30 081238.png…]()

**Comment by sd50pcs2000** [comment]
![屏幕截图 2024-07-30 081238](https://github.com/user-attachments/assets/d46db787-dcd1-4fde-b227-5d0c110542c3)

**Comment by quqiufeng** [comment]
diffusers库不支持最新版的  各种报错

**Comment by Jannchie** [comment]
Fixed...
